import React, { useState, useEffect } from 'react';
import { useAuth } from '../hooks/useAuth';
import { useTracking } from '../hooks/useTracking';
import { motion, AnimatePresence } from 'framer-motion';
import { LogOut, Navigation, StopCircle, PlayCircle, MapPin, Map as MapIcon, ShieldAlert, CheckCircle2, ShieldCheck } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { db } from '../lib/firebase';
import { ref, get } from 'firebase/database';

export default function FieldUser() {
  const { currentUser, logout } = useAuth();
  const userName = currentUser?.displayName || currentUser?.email?.split('@')[0] || 'User';
  const { isTracking, startTracking, stopTracking, currentLocation, tripData, error, syncError } = useTracking(currentUser?.uid, userName);
  const navigate = useNavigate();
  const [isSharing, setIsSharing] = useState(false);

  const handleLogout = async () => {
    if (isTracking) {
      await stopTracking();
    }
    await logout();
    navigate('/login');
  };

  const handleStopTracking = async () => {
    try {
      const summary = await stopTracking();
      if (summary) {
        handleWhatsAppShare(summary);
      }
    } catch (err) {
      console.error("Error stopping tracking", err);
    }
  };

  const handleWhatsAppShare = async (data = tripData) => {
    if (!data) return;
    setIsSharing(true);

    try {
      const settingsRef = ref(db, 'settings/whatsappNumbers');
      const snapshot = await get(settingsRef);

      let targetNumbers = ['9361123970']; // Default number
      if (snapshot.exists()) {
        const val = snapshot.val();
        const configuredNumbers = Object.values(val);
        if (configuredNumbers.length > 0) {
          targetNumbers = configuredNumbers;
        }
      }

      const text = `🚀 *Trip Report - Geofleet*\n\n👤 *User:* ${userName}\n📏 *Distance:* ${data.distanceKm} km\n⏱️ *Duration:* ${(data.durationSeconds / 60).toFixed(1)} mins\n📅 *Date:* ${new Date().toLocaleDateString()}\n\n_Generated by Geofleet Tracking App_`;

      const primaryNumber = targetNumbers[0].replace(/[^0-9]/g, '');
      const waUrl = `https://wa.me/${primaryNumber.length === 10 ? '91' + primaryNumber : primaryNumber}?text=${encodeURIComponent(text)}`;

      const result = window.open(waUrl, '_blank');
      if (!result) {
        window.location.href = waUrl;
      }
    } catch (err) {
      console.error("Error sharing to WhatsApp", err);
    } finally {
      setIsSharing(false);
    }
  };

  return (
    <div className="relative min-h-screen flex flex-col bg-background overflow-hidden p-6 max-w-md mx-auto">
      {/* Dynamic Background */}
      <div className="absolute inset-0 z-0 pointer-events-none">
        <motion.div
          animate={{
            scale: isTracking ? [1, 1.2, 1] : 1,
            opacity: isTracking ? 0.4 : 0.1,
          }}
          transition={{ duration: 4, repeat: Infinity }}
          className="absolute top-1/4 left-1/4 w-[500px] h-[500px] bg-primary/30 rounded-full blur-[120px] -translate-x-1/2 -translate-y-1/2"
        />
        <motion.div
          animate={{
            scale: isTracking ? [1, 1.3, 1] : 1,
            opacity: isTracking ? 0.3 : 0.1,
          }}
          transition={{ duration: 5, repeat: Infinity, delay: 1 }}
          className={`absolute bottom-1/4 right-1/4 w-[400px] h-[400px] rounded-full blur-[100px] translate-x-1/2 translate-y-1/2 ${isTracking ? 'bg-success/30' : 'bg-primary/20'}`}
        />
      </div>

      {/* Header */}
      <header className="flex justify-between items-center mb-12 relative z-10 pt-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-white mb-1">Hi, {userName}</h1>
          <p className="text-white/60 font-medium">Ready for your trip?</p>
        </div>
        <button
          onClick={handleLogout}
          className="p-3 bg-white/5 hover:bg-white/10 rounded-full border border-white/10 transition-colors"
        >
          <LogOut className="w-5 h-5 text-white/80" />
        </button>
      </header>

      {/* Main Content Area */}
      <main className="flex-1 flex flex-col items-center justify-center relative z-10">
        <div className="glass-card w-full p-8 flex flex-col items-center justify-center mb-8 relative overflow-hidden">
          {/* Status Indicator */}
          <div className="absolute top-4 left-4 flex items-center gap-2 px-3 py-1.5 rounded-full bg-black/40 border border-white/10 text-sm font-medium">
            <motion.div
              animate={{ opacity: isTracking ? [1, 0.4, 1] : 1 }}
              transition={{ duration: 1.5, repeat: Infinity }}
              className={`w-2.5 h-2.5 rounded-full ${isTracking ? 'bg-success' : 'bg-white/30'}`}
            />
            {isTracking ? 'Active' : 'Offline'}
          </div>

          <motion.div
            className="mt-12 mb-8 relative"
            animate={isTracking ? { y: [0, -10, 0] } : {}}
            transition={{ duration: 3, repeat: Infinity, ease: "easeInOut" }}
          >
            <div className={`p-6 rounded-full border-2 ${isTracking ? 'border-success/50 bg-success/10' : 'border-white/10 bg-white/5'}`}>
              <Navigation className={`w-16 h-16 ${isTracking ? 'text-success drop-shadow-[0_0_15px_rgba(34,197,94,0.5)]' : 'text-white/50'}`} />
            </div>

            {/* Ripple effect when tracking */}
            <AnimatePresence>
              {isTracking && (
                <motion.div
                  initial={{ opacity: 0.8, scale: 0.8 }}
                  animate={{ opacity: 0, scale: 2 }}
                  exit={{ opacity: 0 }}
                  transition={{ duration: 2, repeat: Infinity }}
                  className="absolute inset-0 rounded-full border-2 border-success"
                />
              )}
            </AnimatePresence>
          </motion.div>

          {/* Location Info */}
          <div className="h-16 flex items-center justify-center w-full">
            {isTracking && currentLocation ? (
              <div className="flex flex-col items-center gap-3">
                <div className="flex items-center gap-2 text-white/80 bg-black/30 px-4 py-2 rounded-xl">
                  <MapPin className="w-4 h-4 text-primary" />
                  <span className="font-mono text-sm tracking-widest">
                    {currentLocation.lat.toFixed(4)}, {currentLocation.lng.toFixed(4)}
                  </span>
                </div>
                
                {syncError ? (
                   <div className="flex items-center gap-1.5 text-[10px] text-danger-400 uppercase tracking-widest font-bold px-3 py-1 bg-danger/5 rounded-full border border-danger/10">
                    <ShieldAlert className="w-3 h-3" />
                    {syncError}
                  </div>
                ) : (
                  <div className="flex items-center gap-1.5 text-[10px] text-success/70 uppercase tracking-widest font-bold px-3 py-1 bg-success/5 rounded-full border border-success/10">
                    <ShieldCheck className="w-3 h-3" />
                    Syncing with Admin...
                  </div>
                )}
              </div>
            ) : error ? (
              <div className="flex items-center gap-2 text-danger-400 bg-danger/10 px-4 py-2 rounded-xl border border-danger/20 text-sm">
                <ShieldAlert className="w-4 h-4" />
                {error}
              </div>
            ) : (
              <div className="text-white/40 text-sm px-4 py-2 italic font-medium">
                {isTracking ? (
                  <span className="flex items-center gap-2 animate-pulse text-primary/70">
                    <Navigation className="w-3 h-3 animate-spin" />
                    Getting GPS fix...
                  </span>
                ) : (
                  tripData ? 'Trip completed and shared!' : 'Press Start to begin tracking'
                )}
              </div>
            )}
          </div>
        </div>
        <div className="w-full space-y-4">
          <AnimatePresence mode="wait">
            {!isTracking ? (
              <motion.button
                key="start"
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                whileTap={{ scale: 0.95 }}
                onClick={startTracking}
                className="w-full relative overflow-hidden group bg-success hover:bg-success/90 text-white font-bold text-lg py-5 rounded-2xl shadow-[0_0_40px_rgba(34,197,94,0.3)] transition-all flex items-center justify-center gap-3"
              >
                <PlayCircle className="w-6 h-6" />
                START TRACKING
                <div className="absolute inset-0 bg-white/10 translate-y-full group-hover:translate-y-0 transition-transform duration-300" />
              </motion.button>
            ) : (
              <motion.button
                key="stop"
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                whileTap={{ scale: 0.95 }}
                onClick={handleStopTracking}
                className="w-full relative overflow-hidden group bg-danger hover:bg-danger/90 text-white font-bold text-lg py-5 rounded-2xl shadow-[0_0_40px_rgba(239,68,68,0.3)] transition-all flex items-center justify-center gap-3"
              >
                <StopCircle className="w-6 h-6" />
                STOP TRACKING
                <div className="absolute inset-0 bg-white/10 translate-y-full group-hover:translate-y-0 transition-transform duration-300" />
              </motion.button>
            )}
          </AnimatePresence>
        </div>
        <AnimatePresence>
          {tripData && !isTracking && (
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              className="absolute inset-x-0 bottom-0 p-6 glass-card border-b-0 rounded-b-none z-20 bg-black/80"
            >
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-bold flex items-center gap-2">
                  <CheckCircle2 className="w-5 h-5 text-success" />
                  Trip Completed
                </h3>
              </div>
              <div className="grid grid-cols-2 gap-4 mb-4">
                <div className="bg-white/5 border border-white/10 rounded-xl p-4 text-center">
                  <p className="text-white/40 text-[10px] uppercase tracking-widest mb-1">Distance</p>
                  <p className="text-xl font-bold">{tripData.distanceKm} km</p>
                </div>
                <div className="bg-white/5 border border-white/10 rounded-xl p-4 text-center">
                  <p className="text-white/40 text-[10px] uppercase tracking-widest mb-1">Time</p>
                  <p className="text-xl font-bold">{(tripData.durationSeconds / 60).toFixed(0)} min</p>
                </div>
              </div>
              <p className="text-xs text-center text-white/40 italic">Report shared automatically via WhatsApp</p>
            </motion.div>
          )}
        </AnimatePresence>
      </main>
    </div>
  );
}
